### PR TITLE
Update to latest KotlinPoet Version

### PR DESCRIPTION
**Pull request by vdubedout**
- Updated Kotlin from 1.1.51 to 1.2.0
- Updated Gradle from 3.0.0 to 3.0.1
- Updated KotlinPoet from 0.6-snapshot to 0.6

[Update to KotlinPoet 0.6 thanks to @mannodermaus Job](https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/389)
[Fix my issue with outdated KotlinPoet version used](https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/415)

### CODE REVIEW

**Comment by mannodermaus** [comment]
Thank you!

**Comment by vdubedout** [comment]
@mannodermaus I've seen this [Todo](https://github.com/ViFork/PermissionsDispatcher/commit/c93929a9f97c6fff5e6dd3c2d57c965946188875)
Do you want me to remove it?
```
// TODO Until #389 is resolved by a proper update to kotlinpoet: https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/389
maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
```

**Comment by hotchemi** [comment]
@vdubedout @mannodermaus thx! I'd say we should remove it~

**Comment by mannodermaus** [comment]
Yeah, that should be removed.

**Pull request merged**
