### PR TITLE
Add support for gradle incremental annotation processing

### PR DESCRIPTION
**Pull request by hotchemi**
## Issue

resolves https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/473

## Overview

This PR adds incremental compilation support. I suppose right now this feature is only for Java? 🤔 

#### Ref

- doc: https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing
- Dagger's issue and commit: https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/473#issuecomment-446132000

### CODE REVIEW

**Comment by autonomousapps** [comment]
Kotlin does not have support for incremental annotation processing yet. There's an open issue, can't find the link...

**Comment by hotchemi** [comment]
@autonomousapps thank you I've just founded on Dagger's repo 🙇 https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/473#issuecomment-446445332

**Comment by technoir42** [comment]
@hotchemi for incremental AP to work you also need to provide an originating element for every generated file.

From the [Gradle documentation](https://docs.gradle.org/4.8/userguide/java_plugin.html#sec:incremental_annotation_processing):
> They must provide exactly one originating element for each file generated with the Filer API. If zero or many originating elements are provided, Gradle will recompile all source files.

For Java you can use `TypeSpec.Builder.addOriginatingElement` but I'm not sure what to use for Kotlin.
Here is relevant commit from Dagger: https://github.com/google/dagger/commit/baf235794459ea8318b89c9c3eb2f9ef5ede846a

**Comment by hotchemi** [comment]
@technoir42 ooh thank you let me address!

**Pull request merged**
