### PR TITLE
Added support of Conductor library

### PR DESCRIPTION
**Pull request by Sar777**

### CODE REVIEW

**Comment by hotchemi** [comment]
👀

**Comment by hotchemi** [comment]
Sorry for the late..code seems nice but I've been considering how to integrate with Coordinator. May be it's better to separate as another library? 🤔

**Comment by Sar777** [comment]
@hotchemi Hi! Yes, it will be also perfectly as another library

**Comment by hotchemi** [comment]
Reopened the issue and let me close the PR for the time being. I suppose we need more considerations for this.

**Pull request closed without merging**
