### PR TITLE
Add handling support fragment's getActivity()

### PR DESCRIPTION
**Pull request by tomoya0x00**
See #483

### CODE REVIEW

**Comment by tomoya0x00** [comment]
🤔

**Comment by hotchemi** [comment]
👀

**Comment by hotchemi** [comment]
^ I think we don't need to check `rpe.isSubtypeOf` because there's no guarantee that activity is not null so just adding null check statement is ok, thx!

**Comment by tomoya0x00** [comment]
OK. I will adding null check every time.

The generated code will be as below.
```java
static void showCameraWithPermissionCheck(MainActivity target) {
  Activity activity = target;
  if (activity == null) return;
  if (PermissionUtils.hasSelfPermissions(activity, PERMISSION_SHOWCAMERA)) {
    target.showCamera();
  } else {
    if (PermissionUtils.shouldShowRequestPermissionRationale(target, PERMISSION_SHOWCAMERA)) {
      target.showRationaleForCamera(new MainActivityShowCameraPermissionRequest(target));
    } else {
      ActivityCompat.requestPermissions(target, PERMISSION_SHOWCAMERA, REQUEST_SHOWCAMERA);
    }
  }
}
```

If checking that target inherits Activity is as below.
```java
static void showCameraWithPermissionCheck(MainActivity target) {
  if (target == null) return;
  if (PermissionUtils.hasSelfPermissions(target, PERMISSION_SHOWCAMERA)) {
    target.showCamera();
  } else {
    if (PermissionUtils.shouldShowRequestPermissionRationale(target, PERMISSION_SHOWCAMERA)) {
      target.showRationaleForCamera(new MainActivityShowCameraPermissionRequest(target));
    } else {
      ActivityCompat.requestPermissions(target, PERMISSION_SHOWCAMERA, REQUEST_SHOWCAMERA);
    }
  }
}
```

Which do you think is better?

**Comment by hotchemi** [comment]
I think the latter is better! Thank you for your suggestion 😃

**Comment by hotchemi** [comment]
Oh sorry for the late..can I ask the current status of this PR? 👀 @tomoya0x00

**Comment by hotchemi** [comment]
@tomoya0x00 Sorry for the late and let me share my idea.

- I noticed we can solve this problem in most cases by adding `NonNull` annotation.

```java
static void showCameraWithPermissionCheck(@NonNull MyActivity target) {
}
```

- The only exceptional case is getting activity from fragment, but we expect that fragment is attached to an activity so we can use `requireActivity` method which is included in new support library.

```diff
- Activity activity = target.getActivity();
+ Activity activity = target.requireActivity();
```

It would cause `IllegalStateException` but I think it's better to notify developer that something wrong is happening, rather than do nothing.

So I wanna close this PR(really sorry for that). I'd create new PR but if you wanna continue working on it let us know 🙇 Thank you for your great work!

**Pull request closed without merging**
